function makeOptions(items) {
  return items.map((item) => ({
    value: item,
    label: formatLabel(item),
  }))
}

function formatLabel(value) {
  const dictionary = {
    none: 'Nenhum',

    default: 'Padrão',
    happy: 'Feliz',
    hearts: 'Corações',
    side: 'Lado',
    squint: 'Apertados',
    surprised: 'Surpreso',
    wink: 'Piscando',
    winkWacky: 'Piscada maluca',
    xDizzy: 'Tonto',
    cry: 'Chorando',
    close: 'Fechados',
    closed: 'Fechados',
    eyeRoll: 'Olhar torto',

    defaultNatural: 'Natural',
    angry: 'Bravo',
    angryNatural: 'Bravo natural',
    flatNatural: 'Reta natural',
    frownNatural: 'Carrancuda natural',
    raisedExcited: 'Animada',
    raisedExcitedNatural: 'Animada natural',
    sadConcerned: 'Triste',
    sadConcernedNatural: 'Triste natural',
    unibrowNatural: 'Unida natural',
    upDown: 'Alta e baixa',
    upDownNatural: 'Alta/baixa natural',

    smile: 'Sorriso',
    serious: 'Séria',
    twinkle: 'Brilho',
    eating: 'Comendo',
    grimace: 'Careta',
    sad: 'Triste',
    screamOpen: 'Grito',
    tongue: 'Língua',
    vomit: 'Enjoo',

    bigHair: 'Volumoso',
    bob: 'Bob',
    bun: 'Coque',
    curly: 'Cacheado',
    curvy: 'Curvado',
    dreads: 'Dreads',
    dreads01: 'Dreads 1',
    dreads02: 'Dreads 2',
    frida: 'Frida',
    frizzle: 'Frizz',
    fro: 'Black power',
    froBand: 'Black com faixa',
    hat: 'Chapéu',
    hijab: 'Hijab',
    longButNotTooLong: 'Longo',
    miaWallace: 'Mia Wallace',
    shaggy: 'Bagunçado',
    shaggyMullet: 'Mullet',
    shavedSides: 'Laterais raspadas',
    shortCurly: 'Curto cacheado',
    shortFlat: 'Curto liso',
    shortRound: 'Curto arredondado',
    shortWaved: 'Curto ondulado',
    sides: 'Laterais',
    straight01: 'Liso 1',
    straight02: 'Liso 2',
    straightAndStrand: 'Liso com mecha',
    theCaesar: 'Caesar',
    theCaesarAndSidePart: 'Caesar lateral',
    turban: 'Turbante',
    winterHat1: 'Touca 1',
    winterHat02: 'Touca 2',
    winterHat03: 'Touca 3',
    winterHat04: 'Touca 4',

    blazerAndShirt: 'Blazer camisa',
    blazerAndSweater: 'Blazer suéter',
    collarAndSweater: 'Gola suéter',
    graphicShirt: 'Camisa estampada',
    hoodie: 'Moletom',
    overall: 'Jardineira',
    shirtCrewNeck: 'Gola careca',
    shirtScoopNeck: 'Gola aberta',
    shirtVNeck: 'Gola V',

    eyepatch: 'Tapa-olho',
    kurt: 'Brinco',
    prescription01: 'Óculos 1',
    prescription02: 'Óculos 2',
    round: 'Redondo',
    sunglasses: 'Escuros',
    wayfarers: 'Wayfarer',

    beardMedium: 'Barba média',
    beardLight: 'Barba leve',
    beardMajestic: 'Barba cheia',
    moustacheFancy: 'Bigode fino',
    moustacheMagnum: 'Bigode Magnum',

    light: 'Claro',
    yellow: 'Amarelado',
    tanned: 'Bronzeado',
    brown: 'Moreno',
    darkBrown: 'Marrom escuro',
    black: 'Negro',

    b6e3f4: 'Azul claro',
    c0aede: 'Lilás',
    d1d4f9: 'Lavanda',
    ffd5dc: 'Rosa claro',
    ffdfbf: 'Pêssego',
    fef08a: 'Amarelo',
    bbf7d0: 'Verde claro',
    bfdbfe: 'Azul suave',
    fecaca: 'Rosé',
  }

  return dictionary[value] || value
}

export const avatarOptions = {
  eyes: makeOptions([
    'default',
    'happy',
    'hearts',
    'side',
    'squint',
    'surprised',
    'wink',
    'winkWacky',
    'xDizzy',
    'cry',
    'closed',
    'eyeRoll',
  ]),
  eyebrows: makeOptions([
    'default',
    'defaultNatural',
    'angry',
    'angryNatural',
    'flatNatural',
    'frownNatural',
    'raisedExcited',
    'raisedExcitedNatural',
    'sadConcerned',
    'sadConcernedNatural',
    'unibrowNatural',
    'upDown',
    'upDownNatural',
  ]),
  mouth: makeOptions([
    'default',
    'smile',
    'serious',
    'twinkle',
    'eating',
    'grimace',
    'sad',
    'screamOpen',
    'tongue',
    'vomit',
  ]),
  top: makeOptions([
    'bigHair',
    'bob',
    'bun',
    'curly',
    'curvy',
    'dreads',
    'dreads01',
    'dreads02',
    'frida',
    'frizzle',
    'fro',
    'froBand',
    'hat',
    'hijab',
    'longButNotTooLong',
    'miaWallace',
    'shaggy',
    'shaggyMullet',
    'shavedSides',
    'shortCurly',
    'shortFlat',
    'shortRound',
    'shortWaved',
    'sides',
    'straight01',
    'straight02',
    'straightAndStrand',
    'theCaesar',
    'theCaesarAndSidePart',
    'turban',
    'winterHat1',
    'winterHat02',
    'winterHat03',
    'winterHat04',
  ]),
  clothing: makeOptions([
    'blazerAndShirt',
    'blazerAndSweater',
    'collarAndSweater',
    'graphicShirt',
    'hoodie',
    'overall',
    'shirtCrewNeck',
    'shirtScoopNeck',
    'shirtVNeck',
  ]),
  accessories: makeOptions([
    'none',
    'eyepatch',
    'kurt',
    'prescription01',
    'prescription02',
    'round',
    'sunglasses',
    'wayfarers',
  ]),
  facialHair: makeOptions([
    'none',
    'beardMedium',
    'beardLight',
    'beardMajestic',
    'moustacheFancy',
    'moustacheMagnum',
  ]),
  skinColor: makeOptions([
    'light',
    'yellow',
    'tanned',
    'brown',
    'darkBrown',
    'black',
  ]),
  backgroundColor: makeOptions([
    'b6e3f4',
    'c0aede',
    'd1d4f9',
    'ffd5dc',
    'ffdfbf',
    'fef08a',
    'bbf7d0',
    'bfdbfe',
    'fecaca',
  ]),
}